{- |
Module      :  $Header$
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  : nevrenato@gmail.com
Stability   : experimental
Portability : portable

Description :
Alloy grammar.
-}

module Alloy.AS_Alloy where

import Common.Id



-- DrIFT command
{-! global: GetRange !-}

data X = A | B

-- Generated by DrIFT, look but don't touch!

instance GetRange X where
  getRange = const nullRange
  rangeSpan x = case x of
    A -> []
    B -> []
