{- |
Module      :  $Header$
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  : nevrenato@gmail.com
Stability   : experimental
Portability : portable

Description :
Alloy grammar.
-}

module Alloy.AS_Alloy where

import Common.Id
import Data.Monoid

-- DrIFT command
{-! global: GetRange !-}

data X = X deriving Show

data Sen = Sen deriving (Show,Eq,Ord)

instance Monoid X where
         mempty = undefined
         mappend = undefined


data Symbol = Symbol deriving (Show,Eq,Ord)
data RawSymbol = RawSymbol deriving (Show,Eq,Ord)
data SymbItems = SymbItems deriving (Show,Eq)
data SymbMapItems = SymbMapItems deriving (Show,Eq)

-- Generated by DrIFT, look but don't touch!

instance GetRange X where
  getRange = const nullRange
  rangeSpan x = case x of
    X -> []

instance GetRange Sen where
  getRange = const nullRange
  rangeSpan x = case x of
    Sen -> []

instance GetRange Symbol where
  getRange = const nullRange
  rangeSpan x = case x of
    Symbol -> []

instance GetRange RawSymbol where
  getRange = const nullRange
  rangeSpan x = case x of
    RawSymbol -> []

instance GetRange SymbItems where
  getRange = const nullRange
  rangeSpan x = case x of
    SymbItems -> []

instance GetRange SymbMapItems where
  getRange = const nullRange
  rangeSpan x = case x of
    SymbMapItems -> []
