{-# OPTIONS -w -O0 #-}
{-# LANGUAGE CPP, StandaloneDeriving, DeriveDataTypeable #-}
{- |
Module      :  Alloy/ATC_Alloy.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI GmbH 2012
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(derive Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'Alloy.AS_Alloy.X'
'Alloy.AS_Alloy.Sen'
'Alloy.AS_Alloy.Symbol'
'Alloy.AS_Alloy.RawSymbol'
'Alloy.AS_Alloy.SymbItems'
'Alloy.AS_Alloy.SymbMapItems'
'Alloy.AlloySign.Sign'
'Alloy.AlloySign.Mor'
-}

{-
Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
Alloy/AS_Alloy.hs
Alloy/AlloySign.hs
-}

module Alloy.ATC_Alloy () where

import ATC.AS_Annotation
import ATerm.Lib
import Alloy.AS_Alloy
import Alloy.AlloySign
import Common.Id
import Data.Monoid
import Data.Typeable

{-! for Alloy.AS_Alloy.X derive : Typeable !-}
{-! for Alloy.AS_Alloy.Sen derive : Typeable !-}
{-! for Alloy.AS_Alloy.Symbol derive : Typeable !-}
{-! for Alloy.AS_Alloy.RawSymbol derive : Typeable !-}
{-! for Alloy.AS_Alloy.SymbItems derive : Typeable !-}
{-! for Alloy.AS_Alloy.SymbMapItems derive : Typeable !-}
{-! for Alloy.AlloySign.Sign derive : Typeable !-}
{-! for Alloy.AlloySign.Mor derive : Typeable !-}

{-! for Alloy.AS_Alloy.X derive : ShATermConvertible !-}
{-! for Alloy.AS_Alloy.Sen derive : ShATermConvertible !-}
{-! for Alloy.AS_Alloy.Symbol derive : ShATermConvertible !-}
{-! for Alloy.AS_Alloy.RawSymbol derive : ShATermConvertible !-}
{-! for Alloy.AS_Alloy.SymbItems derive : ShATermConvertible !-}
{-! for Alloy.AS_Alloy.SymbMapItems derive : ShATermConvertible !-}
{-! for Alloy.AlloySign.Sign derive : ShATermConvertible !-}
{-! for Alloy.AlloySign.Mor derive : ShATermConvertible !-}
