{-# OPTIONS -w -O0 #-}
{-# LANGUAGE CPP, StandaloneDeriving, DeriveDataTypeable #-}
{- |
Module      :  Alloy/ATC_Alloy.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI GmbH 2012
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(derive Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'Alloy.AS_Alloy.X'
-}

{-
Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
Alloy/AS_Alloy.hs
Alloy/AlloySign.hs
-}

module Alloy.ATC_Alloy () where

import ATC.AS_Annotation
import ATerm.Lib
import Alloy.AS_Alloy
import Alloy.AlloySign
import Common.Id
import Data.Typeable

{-! for Alloy.AS_Alloy.X derive : Typeable !-}

{-! for Alloy.AS_Alloy.X derive : ShATermConvertible !-}

-- Generated by DrIFT, look but don't touch!

instance ShATermConvertible X where
  toShATermAux att0 xv = case xv of
    A -> return $ addATerm (ShAAppl "A" [] []) att0
    B -> return $ addATerm (ShAAppl "B" [] []) att0
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "A" [] _ -> (att0, A)
    ShAAppl "B" [] _ -> (att0, B)
    u -> fromShATermError "X" u

deriving instance Typeable X
